rougeth/calendaryo

- conferencias/python-brazil-2019/talks_oct_25.toml
- conferencias/python-brazil-2019/talks_oct_26.toml
Also some minor changes to times and rooms
> Added Arthur Fortes and modified Juliany Raiol entry

- conferencias/python-brazil-2019/lightning_talks.toml
- conferencias/python-brazil-2019/meals.toml
- conferencias/python-brazil-2019/talks_oct_25.toml
- conferencias/python-brazil-2019/talks_oct_27.toml
- lightning talks
- credenciamento
- abertura
- encerramento
> Add missing data

- conferencias/python-brazil-2019/tutorials_oct_23.toml
- conferencias/python-brazil-2019/tutorials_oct_24.toml
References: https://docs.google.com/spreadsheets/d/1ZWqcQ_ujRnzHgG3XocCYbuRZdXdYHqpQY3F3C0aV29A/edit#gid=1918550614
> Add tutorials room names

- conferencias/python-brazil-2020/tutoriais.toml
- Python Brasil 2020 . Tutorials schedule
> Added pybr-2020-tutoriais schedule

- conferencias/python-brazil-2020/palestras.toml
- Talks dates
- Capitalized Rodrigo name
> Changed palestras dates and capitalize names

- conferencias/python-brazil-2020/palestras.toml
Reajuste do título da palestra de Ronald Farias
> Alteração do título da palestra de Ronald Farias

- conferencias/python-brazil-2020/palestras.toml
Alteração da descrição para melhor formatação da palestra de Alejandro Mesias
> Alteração da descrição de palestra

- conferencias/python-brazil-2020/palestras.toml
Troca dos horários das palestras entre Luís Vinicius e Otavio.
> Troca dos horários das palestras

- conferencias/python-brazil-2020/keynotes.toml
Adicionando arquivo toml com Keynotes
> add keynotes toml

- conferencias/python-brazil-2020/mesa-redonda.toml
> Ajustando tempo de abertura

- conferencias/python-brazil-2020/palestras.toml
> Dessa desc

- conferencias/python-brazil-2020/tutoriais.toml
> Mudando hora tutorias tarde

- conferencias/python-brazil-2020/sprints.toml
- conferencias/python-brazil-2020/tutoriais.toml
Ricardo teve um problema pessoal e não pôde ministrar seu tutorial, por isso foi assumido em caráter de urgência pelo professor Glauco, que já era participante do evento e conhecido de outra ministrante, para que as atividades prosseguissem.
Fernanda pediu para alterar o horário de seu sprint de 14h para 10h.
> Atualização do horário do sprint da Fernanda e substituição do tutorial do Ricardo pelo tutorial do Glauco

- conferencias/python-brazil-2021/keynotes.toml
* Roda de Quinta e Sexta estavão invertidas
> Ajustando Rodas de Quinta e Sexta

- conferencias/python-brazil-2021/keynotes.toml
Ajustando  Keynote Final e Encerramento
> Ajustando Keynote Final e Encerramento

- conferencias/python-brazil-2021/palestras.toml
Adicionando discord_channel para gerar lembretes nos canais
> Adicionado discord_channel

- conferencias/python-brazil-2021/keynotes.toml
- conferencias/python-brazil-2021/palestras.toml
> Change discod

- conferencias/python-brazil-2021/palestras.toml
https://github.com/pythonbrasil/pybr2021-org/issues/300
> Fix issue #300.

- conferencias/python-brazil-2021/palestras.toml
Please add 'hacktoberfest-accepted' label if possible.
Great event! 🐍
> Add all times for Bonnie Prado Pinto on 13/10

- conferencias/python-brazil-2021/keynotes.toml
- conferencias/python-brazil-2021/relampagos.toml
* Add tempos para https://github.com/pythonbrasil/pybr2021-org/issues/311
* Fix relampago link
To pythonbrasil/pybr2021-org/issues/311
> Cut videos 311

- conferencias/python-brazil-2021/palestras.toml
https://github.com/pythonbrasil/pybr2021-org/issues/315
> Adiciona tempos de corte da trilha Bonnie Prado Pinto do dia 15/10
